import type { Airport } from './types';

export const AIRPORTS: Record<string, Airport> = {
  // Portugal
  LPPT: { city: "Lisbon",         country: "Portugal",     flag: "\u{1F1F5}\u{1F1F9}" },
  LPPR: { city: "Porto",          country: "Portugal",     flag: "\u{1F1F5}\u{1F1F9}" },
  LPFR: { city: "Faro",           country: "Portugal",     flag: "\u{1F1F5}\u{1F1F9}" },
  LPMA: { city: "Madeira",        country: "Portugal",     flag: "\u{1F1F5}\u{1F1F9}" },
  LPLA: { city: "Lajes / Terceira", country: "Azores",    flag: "\u{1F1F5}\u{1F1F9}" },
  LPPD: { city: "Ponta Delgada",  country: "Azores",       flag: "\u{1F1F5}\u{1F1F9}" },
  LPFL: { city: "Flores",         country: "Azores",       flag: "\u{1F1F5}\u{1F1F9}" },
  LPHR: { city: "Horta",          country: "Azores",       flag: "\u{1F1F5}\u{1F1F9}" },
  LPAZ: { city: "Santa Maria",    country: "Azores",       flag: "\u{1F1F5}\u{1F1F9}" },
  LPSJ: { city: "S\u{e3}o Jorge", country: "Azores",       flag: "\u{1F1F5}\u{1F1F9}" },
  LPCO: { city: "Corvo",          country: "Azores",       flag: "\u{1F1F5}\u{1F1F9}" },
  LPGR: { city: "Graciosa",       country: "Azores",       flag: "\u{1F1F5}\u{1F1F9}" },
  LPSC: { city: "Santa Cruz da Graciosa", country: "Azores", flag: "\u{1F1F5}\u{1F1F9}" },
  LPBJ: { city: "Beja",           country: "Portugal",     flag: "\u{1F1F5}\u{1F1F9}" },
  LPEV: { city: "\u{c9}vora",     country: "Portugal",     flag: "\u{1F1F5}\u{1F1F9}" },
  LPCS: { city: "Cascais",        country: "Portugal",     flag: "\u{1F1F5}\u{1F1F9}" },

  // Spain
  LEMD: { city: "Madrid",         country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEBL: { city: "Barcelona",      country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEPA: { city: "Palma",          country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEIB: { city: "Ibiza",          country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEMH: { city: "Menorca",        country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEZL: { city: "Seville",        country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEGR: { city: "Granada",        country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEMG: { city: "M\u{e1}laga",    country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEVX: { city: "Vigo",           country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LECO: { city: "A Coru\u{f1}a",  country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEBB: { city: "Bilbao",         country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEAM: { city: "Almer\u{ed}a",   country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEAL: { city: "Alicante",       country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LEVC: { city: "Valencia",       country: "Spain",        flag: "\u{1F1EA}\u{1F1F8}" },
  LXGB: { city: "Gibraltar",      country: "Gibraltar",    flag: "\u{1F1EC}\u{1F1EE}" },

  // UK
  EGLL: { city: "London Heathrow", country: "UK",          flag: "\u{1F1EC}\u{1F1E7}" },
  EGKK: { city: "London Gatwick", country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },
  EGSS: { city: "London Stansted", country: "UK",          flag: "\u{1F1EC}\u{1F1E7}" },
  EGGW: { city: "London Luton",   country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },
  EGCC: { city: "Manchester",     country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },
  EGPH: { city: "Edinburgh",      country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },
  EGPF: { city: "Glasgow",        country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },
  EGBB: { city: "Birmingham",     country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },
  EGGD: { city: "Bristol",        country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },
  EGMC: { city: "London Southend", country: "UK",          flag: "\u{1F1EC}\u{1F1E7}" },
  EGAA: { city: "Belfast",        country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },
  EGNT: { city: "Newcastle",      country: "UK",           flag: "\u{1F1EC}\u{1F1E7}" },

  // France
  LFPG: { city: "Paris CDG",      country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFPO: { city: "Paris Orly",     country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFBO: { city: "Toulouse",       country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFML: { city: "Marseille",      country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFMN: { city: "Nice",           country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFLY: { city: "Lyon",           country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFLL: { city: "Lyon",           country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFRN: { city: "Rennes",         country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFBD: { city: "Bordeaux",       country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },
  LFRS: { city: "Nantes",         country: "France",       flag: "\u{1F1EB}\u{1F1F7}" },

  // Germany
  EDDF: { city: "Frankfurt",      country: "Germany",      flag: "\u{1F1E9}\u{1F1EA}" },
  EDDM: { city: "Munich",         country: "Germany",      flag: "\u{1F1E9}\u{1F1EA}" },
  EDDB: { city: "Berlin",         country: "Germany",      flag: "\u{1F1E9}\u{1F1EA}" },
  EDDH: { city: "Hamburg",        country: "Germany",      flag: "\u{1F1E9}\u{1F1EA}" },
  EDDK: { city: "Cologne",        country: "Germany",      flag: "\u{1F1E9}\u{1F1EA}" },
  EDDL: { city: "D\u{fc}sseldorf", country: "Germany",     flag: "\u{1F1E9}\u{1F1EA}" },
  EDDS: { city: "Stuttgart",      country: "Germany",      flag: "\u{1F1E9}\u{1F1EA}" },

  // Netherlands & Belgium
  EHAM: { city: "Amsterdam",      country: "Netherlands",  flag: "\u{1F1F3}\u{1F1F1}" },
  EBBR: { city: "Brussels",       country: "Belgium",      flag: "\u{1F1E7}\u{1F1EA}" },
  EBCI: { city: "Charleroi",      country: "Belgium",      flag: "\u{1F1E7}\u{1F1EA}" },

  // Switzerland, Austria & Luxembourg
  LSZH: { city: "Zurich",         country: "Switzerland",  flag: "\u{1F1E8}\u{1F1ED}" },
  LSGG: { city: "Geneva",         country: "Switzerland",  flag: "\u{1F1E8}\u{1F1ED}" },
  LSZA: { city: "Lugano",         country: "Switzerland",  flag: "\u{1F1E8}\u{1F1ED}" },
  LSGK: { city: "Saanen",         country: "Switzerland",  flag: "\u{1F1E8}\u{1F1ED}" },
  LOWW: { city: "Vienna",         country: "Austria",      flag: "\u{1F1E6}\u{1F1F9}" },
  LOWI: { city: "Innsbruck",      country: "Austria",      flag: "\u{1F1E6}\u{1F1F9}" },
  ELLX: { city: "Luxembourg",     country: "Luxembourg",   flag: "\u{1F1F1}\u{1F1FA}" },

  // Italy
  LIRF: { city: "Rome Fiumicino", country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },
  LIMC: { city: "Milan Malpensa", country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },
  LIML: { city: "Milan Linate",   country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },
  LIME: { city: "Bergamo",        country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },
  LIPZ: { city: "Venice",         country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },
  LIRN: { city: "Naples",         country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },
  LIBR: { city: "Brindisi",       country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },
  LICJ: { city: "Palermo",        country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },
  LICR: { city: "Catania",        country: "Italy",        flag: "\u{1F1EE}\u{1F1F9}" },

  // Ireland & Nordic
  EIDW: { city: "Dublin",         country: "Ireland",      flag: "\u{1F1EE}\u{1F1EA}" },
  EICK: { city: "Cork",           country: "Ireland",      flag: "\u{1F1EE}\u{1F1EA}" },
  EINN: { city: "Shannon",        country: "Ireland",      flag: "\u{1F1EE}\u{1F1EA}" },
  ENGM: { city: "Oslo",           country: "Norway",       flag: "\u{1F1F3}\u{1F1F4}" },
  ENZV: { city: "Stavanger",      country: "Norway",       flag: "\u{1F1F3}\u{1F1F4}" },
  ESSA: { city: "Stockholm",      country: "Sweden",       flag: "\u{1F1F8}\u{1F1EA}" },
  ESGG: { city: "Gothenburg",     country: "Sweden",       flag: "\u{1F1F8}\u{1F1EA}" },
  EKCH: { city: "Copenhagen",     country: "Denmark",      flag: "\u{1F1E9}\u{1F1F0}" },
  EFHK: { city: "Helsinki",       country: "Finland",      flag: "\u{1F1EB}\u{1F1EE}" },
  EVRA: { city: "Riga",           country: "Latvia",       flag: "\u{1F1F1}\u{1F1FB}" },
  EYVI: { city: "Vilnius",        country: "Lithuania",    flag: "\u{1F1F1}\u{1F1F9}" },
  EETN: { city: "Tallinn",        country: "Estonia",      flag: "\u{1F1EA}\u{1F1EA}" },

  // Canary Islands
  GCLP: { city: "Gran Canaria",   country: "Spain",        flag: "\u{1F1EE}\u{1F1E8}" },
  GCTS: { city: "Tenerife South", country: "Spain",        flag: "\u{1F1EE}\u{1F1E8}" },
  GCXO: { city: "Tenerife North", country: "Spain",        flag: "\u{1F1EE}\u{1F1E8}" },
  GCRR: { city: "Lanzarote",      country: "Spain",        flag: "\u{1F1EE}\u{1F1E8}" },
  GCFV: { city: "Fuerteventura",  country: "Spain",        flag: "\u{1F1EE}\u{1F1E8}" },
  GCLA: { city: "La Palma",       country: "Spain",        flag: "\u{1F1EE}\u{1F1E8}" },

  // Morocco & North Africa
  GMMN: { city: "Casablanca",     country: "Morocco",      flag: "\u{1F1F2}\u{1F1E6}" },
  GMMJ: { city: "Oujda",          country: "Morocco",      flag: "\u{1F1F2}\u{1F1E6}" },
  GMME: { city: "Rabat",          country: "Morocco",      flag: "\u{1F1F2}\u{1F1E6}" },
  GMAD: { city: "Agadir",         country: "Morocco",      flag: "\u{1F1F2}\u{1F1E6}" },
  GMFF: { city: "Fez",            country: "Morocco",      flag: "\u{1F1F2}\u{1F1E6}" },
  GMMX: { city: "Marrakech",      country: "Morocco",      flag: "\u{1F1F2}\u{1F1E6}" },
  DAAG: { city: "Algiers",        country: "Algeria",      flag: "\u{1F1E9}\u{1F1FF}" },
  DTTA: { city: "Tunis",          country: "Tunisia",      flag: "\u{1F1F9}\u{1F1F3}" },
  DTTJ: { city: "Djerba",         country: "Tunisia",      flag: "\u{1F1F9}\u{1F1F3}" },

  // West Africa & Cape Verde
  GVNP: { city: "Praia",          country: "Cape Verde",   flag: "\u{1F1E8}\u{1F1FB}" },
  GVSV: { city: "S\u{e3}o Vicente", country: "Cape Verde", flag: "\u{1F1E8}\u{1F1FB}" },
  GVBA: { city: "Boa Vista",      country: "Cape Verde",   flag: "\u{1F1E8}\u{1F1FB}" },
  GVSA: { city: "Sal",            country: "Cape Verde",   flag: "\u{1F1E8}\u{1F1FB}" },
  GOBD: { city: "Dakar",          country: "Senegal",      flag: "\u{1F1F8}\u{1F1F3}" },
  DIAP: { city: "Abidjan",        country: "Ivory Coast",  flag: "\u{1F1E8}\u{1F1EE}" },
  DGAA: { city: "Accra",          country: "Ghana",        flag: "\u{1F1EC}\u{1F1ED}" },
  DNMM: { city: "Lagos",          country: "Nigeria",      flag: "\u{1F1F3}\u{1F1EC}" },

  // Southern Africa & Angola
  FNLU: { city: "Luanda",         country: "Angola",       flag: "\u{1F1E6}\u{1F1F4}" },
  FQMA: { city: "Maputo",         country: "Mozambique",   flag: "\u{1F1F2}\u{1F1FF}" },
  FACT: { city: "Cape Town",      country: "South Africa", flag: "\u{1F1FF}\u{1F1E6}" },
  FAOR: { city: "Johannesburg",   country: "South Africa", flag: "\u{1F1FF}\u{1F1E6}" },

  // Brazil
  SBGR: { city: "S\u{e3}o Paulo", country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBBR: { city: "Bras\u{ed}lia",  country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBGL: { city: "Rio de Janeiro", country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBKP: { city: "Campinas",       country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBCF: { city: "Belo Horizonte", country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBSV: { city: "Salvador",       country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBFZ: { city: "Fortaleza",      country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBRF: { city: "Recife",         country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBBE: { city: "Bel\u{e9}m",     country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBMN: { city: "Manaus",         country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBFL: { city: "Florian\u{f3}polis", country: "Brazil",   flag: "\u{1F1E7}\u{1F1F7}" },
  SBPA: { city: "Porto Alegre",   country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBCT: { city: "Curitiba",       country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },
  SBNT: { city: "Natal",          country: "Brazil",       flag: "\u{1F1E7}\u{1F1F7}" },

  // North America
  KJFK: { city: "New York JFK",   country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KEWR: { city: "Newark",         country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KBOS: { city: "Boston",         country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KMIA: { city: "Miami",          country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KIAD: { city: "Washington",     country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KPHL: { city: "Philadelphia",   country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KORD: { city: "Chicago",        country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KATL: { city: "Atlanta",        country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KLAX: { city: "Los Angeles",    country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  KSFO: { city: "San Francisco",  country: "USA",          flag: "\u{1F1FA}\u{1F1F8}" },
  CYYZ: { city: "Toronto",        country: "Canada",       flag: "\u{1F1E8}\u{1F1E6}" },
  CYUL: { city: "Montr\u{e9}al",  country: "Canada",       flag: "\u{1F1E8}\u{1F1E6}" },
  CYVR: { city: "Vancouver",      country: "Canada",       flag: "\u{1F1E8}\u{1F1E6}" },

  // Middle East & Asia
  OMDB: { city: "Dubai",          country: "UAE",          flag: "\u{1F1E6}\u{1F1EA}" },
  OMAA: { city: "Abu Dhabi",      country: "UAE",          flag: "\u{1F1E6}\u{1F1EA}" },
  OOMS: { city: "Muscat",         country: "Oman",         flag: "\u{1F1F4}\u{1F1F2}" },
  OTHH: { city: "Doha",           country: "Qatar",        flag: "\u{1F1F6}\u{1F1E6}" },
  OBBI: { city: "Bahrain",        country: "Bahrain",      flag: "\u{1F1E7}\u{1F1ED}" },
  OJAM: { city: "Amman",          country: "Jordan",       flag: "\u{1F1EF}\u{1F1F4}" },
  OERK: { city: "Riyadh",         country: "Saudi Arabia", flag: "\u{1F1F8}\u{1F1E6}" },
  HECA: { city: "Cairo",          country: "Egypt",        flag: "\u{1F1EA}\u{1F1EC}" },
  HESH: { city: "Sharm el-Sheikh", country: "Egypt",       flag: "\u{1F1EA}\u{1F1EC}" },

  // Eastern Europe
  LCLK: { city: "Larnaca",        country: "Cyprus",       flag: "\u{1F1E8}\u{1F1FE}" },
  LGAV: { city: "Athens",         country: "Greece",       flag: "\u{1F1EC}\u{1F1F7}" },
  LGIR: { city: "Heraklion",      country: "Greece",       flag: "\u{1F1EC}\u{1F1F7}" },
  LGRP: { city: "Rhodes",         country: "Greece",       flag: "\u{1F1EC}\u{1F1F7}" },
  LTBA: { city: "Istanbul",       country: "Turkey",       flag: "\u{1F1F9}\u{1F1F7}" },
  LTFM: { city: "Istanbul",       country: "Turkey",       flag: "\u{1F1F9}\u{1F1F7}" },
  EPWA: { city: "Warsaw",         country: "Poland",       flag: "\u{1F1F5}\u{1F1F1}" },
  EPMO: { city: "Warsaw Modlin",  country: "Poland",       flag: "\u{1F1F5}\u{1F1F1}" },
  LKPR: { city: "Prague",         country: "Czechia",      flag: "\u{1F1E8}\u{1F1FF}" },
  LHBP: { city: "Budapest",       country: "Hungary",      flag: "\u{1F1ED}\u{1F1FA}" },
  LROP: { city: "Bucharest",      country: "Romania",      flag: "\u{1F1F7}\u{1F1F4}" },
  LYBE: { city: "Belgrade",       country: "Serbia",       flag: "\u{1F1F7}\u{1F1F8}" },
  LDZA: { city: "Zagreb",         country: "Croatia",      flag: "\u{1F1ED}\u{1F1F7}" },
  LBSF: { city: "Sofia",          country: "Bulgaria",     flag: "\u{1F1E7}\u{1F1EC}" },
  LJLJ: { city: "Ljubljana",      country: "Slovenia",     flag: "\u{1F1F8}\u{1F1EE}" },
  LZIB: { city: "Bratislava",     country: "Slovakia",     flag: "\u{1F1F8}\u{1F1F0}" },
  UKBB: { city: "Kyiv",           country: "Ukraine",      flag: "\u{1F1FA}\u{1F1E6}" },
  LLBG: { city: "Tel Aviv",       country: "Israel",       flag: "\u{1F1EE}\u{1F1F1}" },
};

export const AIRLINES: Record<string, string> = {
  TAP: "TAP Air Portugal",
  RYR: "Ryanair",
  EZY: "easyJet",
  BAW: "British Airways",
  AFR: "Air France",
  DLH: "Lufthansa",
  IBE: "Iberia",
  AZA: "ITA Airways",
  KLM: "KLM",
  AEA: "Air Europa",
  EIN: "Aer Lingus",
  THY: "Turkish Airlines",
  UAE: "Emirates",
  QTR: "Qatar Airways",
  SWR: "Swiss",
  BEL: "Brussels Airlines",
  VLG: "Vueling",
  WZZ: "Wizz Air",
  TOM: "TUI",
  DTA: "TAAG Angola",
  TCV: "Cabo Verde Airlines",
  LAP: "LATAM",
  LAN: "LATAM",
  TAM: "LATAM Brasil",
  GLO: "GOL",
  AZU: "Azul",
  ONE: "Azul",
  UAL: "United Airlines",
  AAL: "American Airlines",
  DAL: "Delta Air Lines",
  MSC: "Air Cairo",
  RAM: "Royal Air Maroc",
  AIC: "Air India",
  CSN: "China Southern",
  CCA: "Air China",
  SIA: "Singapore Airlines",
  JAL: "Japan Airlines",
  ANA: "ANA",
  AMX: "Aerom\u{e9}xico",
  SKW: "SkyWest",
  GEC: "Lufthansa Cargo",
  NJE: "NetJets",
  LOG: "Loganair",
  EWG: "Eurowings",
  SXS: "SunExpress",
  FIN: "Finnair",
  NAX: "Norwegian",
  NOR: "Norwegian",
  IBK: "Norwegian",
  SAS: "Scandinavian",
  WIF: "Wideroe",
  ENT: "Enter Air",
  SVA: "Saudia",
  ETH: "Ethiopian",
  KQA: "Kenya Airways",
  MGL: "MIAT",
  HVN: "Vietnam Airlines",
  ETD: "Etihad",
  RJA: "Royal Jordanian",
  OMT: "Omni Air",
  GAO: "Gao Air",
  ASL: "Air Serbia",
  CTN: "Croatia Airlines",
  LZB: "Bulgaria Air",
  AUI: "Ukraine International",
  ROT: "TAROM",
  ELY: "El Al",
  DAH: "Air Alg\u{e9}rie",
  MSR: "EgyptAir",
  VRE: "Air C\u{f4}te d'Ivoire",
  APK: "Air Peace",
  FDB: "flydubai",
  KNE: "flynas",
};

export const AIRCRAFT_TYPES: Record<string, string> = {
  A19N: "A319neo", A20N: "A320neo", A21N: "A321neo",
  A318: "A318",    A319: "A319",    A320: "A320",    A321: "A321",
  A332: "A330-200", A333: "A330-300", A338: "A330-800", A339: "A330-900",
  A342: "A340-200", A343: "A340-300", A345: "A340-500", A346: "A340-600",
  A359: "A350-900", A35K: "A350-1000",
  A388: "A380",    A124: "An-124",
  B735: "737-500", B736: "737-600", B737: "737-700", B738: "737-800",
  B739: "737-900", B38M: "737 MAX 8", B39M: "737 MAX 9",
  B744: "747-400", B748: "747-8",
  B752: "757-200", B753: "757-300",
  B762: "767-200", B763: "767-300", B764: "767-400",
  B772: "777-200", B773: "777-300", B77L: "777-200LR", B77W: "777-300ER",
  B788: "787-8",   B789: "787-9",   B78X: "787-10",
  E170: "E170",    E175: "E175",    E190: "E190",    E195: "E195",
  E290: "E190-E2", E295: "E195-E2",
  AT72: "ATR 72",  AT75: "ATR 72-500", AT76: "ATR 72-600",
  DH8D: "Dash 8 Q400",
  CRJ2: "CRJ-200", CRJ7: "CRJ-700", CRJ9: "CRJ-900",
  C56X: "Citation Excel", C68A: "Citation Latitude",
  PC12: "Pilatus PC-12", DH8A: "Dash 8 Q100",
};
